package com.example.demo.security;

import java.security.Key;                   //generate token, validate token
import java.util.Date;

import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;

public class JwtUtil {

    private static final String SECRET = 
            "mysecretkeymysecretkeymysecretkey12";  //This secret proves: token was generated by YOUR server

    private static final Key KEY =
            Keys.hmacShaKeyFor(SECRET.getBytes());  //Convert Secret To Security Key

    public static String generateToken(String username) {

        return Jwts.builder()
                .setSubject(username)
                .setIssuedAt(new Date())
                .setExpiration(
                        new Date(System.currentTimeMillis() + 86400000) //subject, issued at, expired at
                )
                .signWith(KEY)
                .compact();
    }

    public static String extractUsername(String token) {

        return Jwts.parserBuilder()
                .setSigningKey(KEY)
                .build()
                .parseClaimsJws(token)
                .getBody()
                .getSubject();
    }

    public static boolean validateToken(String token) {

        try {
            Jwts.parserBuilder()
                    .setSigningKey(KEY)
                    .build()
                    .parseClaimsJws(token);

            return true;

        } catch (Exception e) {
            return false;
        }
    }
}